import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./utility.css";
import AOSProvider from "@/components/aosInit";
import TabBar from "@/components/tabBar";

const kbFonts = localFont({
  src: [
    { path: "../public/fonts/KBFGDisplayB.ttf", weight: "700" },
    { path: "../public/fonts/KBFGDisplayL.ttf", weight: "400" },
    { path: "../public/fonts/KBFGDisplayM.ttf", weight: "600" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kbFonts.className} antialiased min-h-screen max-w-[620px] mx-auto bg-slate-50`}>
        <AOSProvider>
          {children}

          <TabBar />
        </AOSProvider>
      </body>
    </html>
  );
}
