import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./utility.css";
import "aos/dist/aos.css";

import AOSProvider from "@/components/aosInit";
import TabBar from "@/components/tabBar";
import ResetButton from "@/components/home/resetButton";
import { UserContextProvier } from "@/hooks/user-context";

const kbFonts = localFont({
  src: [
    { path: "../public/fonts/KBFGDisplayB.ttf", weight: "700" },
    { path: "../public/fonts/KBFGDisplayL.ttf", weight: "400" },
    { path: "../public/fonts/KBFGDisplayM.ttf", weight: "600" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kbFonts.className} antialiased min-h-screen max-w-[620px] mx-auto bg-slate-50`}>
        <AOSProvider>
          <UserContextProvier>
            <div className="flex justify-between">
              <h1 className="inline text-lg font-bold px-3 pt-2">
                <span className="text-kb-main">KB</span>국민은행
              </h1>
              <div className="px-3 pt-3">
                <ResetButton />
              </div>
            </div>
            {children}
            <TabBar />
          </UserContextProvier>
        </AOSProvider>
      </body>
    </html>
  );
}
